### ISSUE TITLE
[Solved] GUI repositioned on pause (ESC)

### ISSUE THREAD

**Issue by Astronants** [neuoy/KSPTrajectories#172] opened 2019-12-08 17:55 UTC
The GUI is repositioned to the last saved position (or center of the screen if nothing was saved) when pausing the game with ESC while it is opened.

### Expected behavior
The GUI should not move when pausing the game or should be destroyed and the position saved.

**Comment by mwerle** [comment] 2019-12-09 00:32
If you use the legacy UI or use the resume button instead of pressing ESC again to unpause this won't happen.

The problem is the use of a PopupDialog for the new-look UI.  Possibly the code could hook into the GameEvents.OnPause event to save the current dialog position whenever the game is paused.

Ultimately it seems to be a bug in KSP itself in that it dismissed _all_ PopupDialogs when you press ESC to unpause the game instead of just dismissing the Pause dialog.

**Comment by PiezPiedPy** [comment] 2019-12-10 17:57
The popup is destroyed by KSP when the ESC menu is displayed, this triggers the popup to save it's position.
The problem lies in how KSP uses the popups rect, it is set only in the Alloc method and is not updated by KSP when the popup is moved, thus when the popup is respawned it uses the position first set in the Alloc method and not its current position.
I'm looking at the issue now and will probably use the GameEvent.onGameUnpause to call a method to set the rect to the last saved position before spawning the popup.

**Comment by PiezPiedPy** [comment] 2019-12-10 18:45
This appears to be sorted, well it works for me 😜 so closing.

**Closed by PiezPiedPy** 2019-12-10 18:45 UTC
Labels: bug
