### ISSUE TITLE
[Solved] Toolbar icon is black

### ISSUE THREAD

**Issue by Brusura** [neuoy/KSPTrajectories#145] opened 2018-03-24 13:57 UTC
Screenshot:
https://drive.google.com/open?id=1nMv8VOql_xEk25Aok6S8P9Mit0EwKXnC
https://drive.google.com/open?id=1G9BZ4CaeD2CqLng_EZq9msYzNGtYRoC9

Logs:
wrong files...

KSP:
1.4.1 x64 en ( stock cubes )

Trajectories 2.1.0

**Comment by PiezPiedPy** [comment] 2018-03-24 14:15
Your first output_log link says you are running KSP v1.3.1 ?
Second output_log link gives Error 404

Initialize engine version: 5.4.0p4 (b15b5ae035b7) is the old Unity used in v1.3.1
[KSP Version]: 1.3.1.1891 (WindowsPlayer x64) (x64) en-us ==============================

**Comment by Brusura** [comment] 2018-03-24 14:54
ops...wait a second xD

**Comment by Brusura** [comment] 2018-03-24 15:04
Ok found it in AppData\LocalLow\Squad\Kerbal Space Program

OUTPUT_LOG:
https://drive.google.com/open?id=1A_PT5Wqhw0TAPNMCIxMtCrtcGSpxLjEX

**Comment by PiezPiedPy** [comment] 2018-03-24 15:29
Very strange, everything looks ok in your logs.
The only difference from my install is you have the expansion which I have not purchased yet so I am unable to test but it should make no difference.
Have you tried as a last resort, verifying your install with steam and deleting and reinstalling Trajectories ?
I am at a loss what the problem is at the moment, everything works fine on my install 🤦‍♂️

**Comment by Lurkios** [comment] 2018-03-25 00:39
Just as a mention, it's black for me as well.

**Comment by studentmain** [comment] 2018-03-25 09:02
ksp 1.4.1 zh x64 with expansion, icon works well. Try to update video driver? Is other mod's icon works well?

**Comment by Lurkios** [comment] 2018-03-25 15:20
Latest drivers, and all other mod icons work.
![untitled](https://user-images.githubusercontent.com/27931290/37876691-783dd3fc-301e-11e8-8de2-4d9aa39f5bf3.png)

**Comment by Lurkios** [comment] 2018-03-25 15:20
Latest drivers, and all other mod icons work.

https://imgur.com/a/9Kfji

**Comment by studentmain** [comment] 2018-03-25 15:35
Emmmm... I have no good idea now. Maybe change icon cause the problem. I saw this bug on Kerbal Alarm Clock (it also change itself icon when running) with ksp 1.4 zh a few days ago. Make sure you use latest ksp.
You can try install Trajectory 1.x and Kerbal Alarm Clock and see how them works.

**Comment by Lurkios** [comment] 2018-03-25 15:37
Found the problem, it's the texture resolution setting. If it's not at "Full Res" the icon doesn't work.

**Comment by PiezPiedPy** [comment] 2018-03-25 15:45
@Lurkios Thanks. Gives me an idea as to what may be the problem.

**Comment by PiezPiedPy** [comment] 2018-03-25 15:47
Some other mods devs have reported their icons being fuzzy, maybe a similar problem.
 I've heard KSP has changed the way textures are loaded, I will look into it.

**Comment by PiezPiedPy** [comment] 2018-03-28 13:08
Fixed, so closing
commit : https://github.com/neuoy/KSPTrajectories/commit/8eec61e71e5cb5335bedb09ccb98424174c2be82

**Closed by PiezPiedPy** 2018-03-28 13:08 UTC
Labels: bug
